cc_test(
    name = "polygon_test",
    srcs = ["polygon_test.cc"],
    deps = [
        "//src:polygon",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "primes_test",
    srcs = ["primes_test.cc"],
    deps = [
        "//src:primes",
        "@googletest//:gtest_main",
    ],
)
