cc_test(
    name = "convex_hull_test",
    srcs = ["convex_hull_test.cc"],
    deps = [
        "//src:convex_hull",
        "//src:point",
        "//src:polygon",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "graph_test",
    srcs = ["graph_test.cc"],
    deps = [
        "//src:graph",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "point_test",
    srcs = ["point_test.cc"],
    deps = [
        "//src:point",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "polygon_test",
    srcs = ["polygon_test.cc"],
    deps = [
        "//src:point",
        "//src:polygon",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "primes_test",
    srcs = ["primes_test.cc"],
    deps = [
        "//src:primes",
        "@googletest//:gtest_main",
    ],
)
